channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - protobuf==3.20.3
  - tensorflow-intel==2.18.0
  - tensorflow==2.18.0
name: mlflow-env
